### ISSUE TITLE
Allows invalid formats

### ISSUE THREAD

**Issue by WORMSS** [CrescentSine/iso8601-interval#3]
```ts
dur`PT0.5H0.5S`.ms
```
is not valid.
iso 8601 says only the least significant number can have a decimal.

Also, you don't seem to allow valid formats such as

```ts
dur`P1D`.ms
```
but you have stated as much in your documentation. Was just unexpected.

**Comment by CrescentSine** [comment]
Thank you for your attention to this small project.
First, I'm sorry that I haven't maintained this project for a long time. This is because soon after I finished the current version, I switched to another language in my work, so I stopped using it.
In very early versions I supported formats like **dur 'P1D '.ms**. But I occurred that even though the JS Date doesn't handle, there are leap seconds in the real world. So a day isn't always logically the same as 86,400 seconds (even if the JS Date object doesn't think so), so I chose to use the JS Date object handle the conversion from day to second and not worry about how it's implemented. If there is any way to deal with leap seconds on standard design in the future, I could migrate to that.
So I split up the code that interprets the template so that **dur** always deals with minutes and seconds, and **per** always deals with years, months, days, or weeks. Use the **toDuration** method to convert a **per** to a **dur** based on a starting time point.
The problem is that **invl**, which combines the two, is simply glues them together and isn't easy to use. I think I can consider to give a cleaner way to improve the use of **invl** in future.

**Comment by WORMSS** [comment]
No problem mate. It seems iso8601 durations is a bit of a forgotten feature for the whole dev community. Even our own team came up with it's own implementation until duration was discovered. Been searching for a bulletproof parser and not actually found a single one yet.
